/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterOverridePolicies implements ClusterOverridePolicyInterface
type FakeClusterOverridePolicies struct {
	Fake *FakePolicyV1alpha1
}

var clusteroverridepoliciesResource = schema.GroupVersionResource{Group: "policy.karmada.io", Version: "v1alpha1", Resource: "clusteroverridepolicies"}

var clusteroverridepoliciesKind = schema.GroupVersionKind{Group: "policy.karmada.io", Version: "v1alpha1", Kind: "ClusterOverridePolicy"}

// Get takes name of the clusterOverridePolicy, and returns the corresponding clusterOverridePolicy object, and an error if there is any.
func (c *FakeClusterOverridePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterOverridePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusteroverridepoliciesResource, name), &v1alpha1.ClusterOverridePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOverridePolicy), err
}

// List takes label and field selectors, and returns the list of ClusterOverridePolicies that match those selectors.
func (c *FakeClusterOverridePolicies) List(opts v1.ListOptions) (result *v1alpha1.ClusterOverridePolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusteroverridepoliciesResource, clusteroverridepoliciesKind, opts), &v1alpha1.ClusterOverridePolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterOverridePolicyList{}
	for _, item := range obj.(*v1alpha1.ClusterOverridePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterOverridePolicies.
func (c *FakeClusterOverridePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusteroverridepoliciesResource, opts))
}

// Create takes the representation of a clusterOverridePolicy and creates it.  Returns the server's representation of the clusterOverridePolicy, and an error, if there is any.
func (c *FakeClusterOverridePolicies) Create(clusterOverridePolicy *v1alpha1.ClusterOverridePolicy) (result *v1alpha1.ClusterOverridePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusteroverridepoliciesResource, clusterOverridePolicy), &v1alpha1.ClusterOverridePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOverridePolicy), err
}

// Update takes the representation of a clusterOverridePolicy and updates it. Returns the server's representation of the clusterOverridePolicy, and an error, if there is any.
func (c *FakeClusterOverridePolicies) Update(clusterOverridePolicy *v1alpha1.ClusterOverridePolicy) (result *v1alpha1.ClusterOverridePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusteroverridepoliciesResource, clusterOverridePolicy), &v1alpha1.ClusterOverridePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOverridePolicy), err
}

// Delete takes name of the clusterOverridePolicy and deletes it. Returns an error if one occurs.
func (c *FakeClusterOverridePolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusteroverridepoliciesResource, name), &v1alpha1.ClusterOverridePolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterOverridePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusteroverridepoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterOverridePolicyList{})
	return err
}

// Patch applies the patch and returns the patched clusterOverridePolicy.
func (c *FakeClusterOverridePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterOverridePolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusteroverridepoliciesResource, name, data, subresources...), &v1alpha1.ClusterOverridePolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterOverridePolicy), err
}
