/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterPropagationPolicies implements ClusterPropagationPolicyInterface
type FakeClusterPropagationPolicies struct {
	Fake *FakePolicyV1alpha1
}

var clusterpropagationpoliciesResource = schema.GroupVersionResource{Group: "policy.karmada.io", Version: "v1alpha1", Resource: "clusterpropagationpolicies"}

var clusterpropagationpoliciesKind = schema.GroupVersionKind{Group: "policy.karmada.io", Version: "v1alpha1", Kind: "ClusterPropagationPolicy"}

// Get takes name of the clusterPropagationPolicy, and returns the corresponding clusterPropagationPolicy object, and an error if there is any.
func (c *FakeClusterPropagationPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterpropagationpoliciesResource, name), &v1alpha1.ClusterPropagationPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagationPolicy), err
}

// List takes label and field selectors, and returns the list of ClusterPropagationPolicies that match those selectors.
func (c *FakeClusterPropagationPolicies) List(opts v1.ListOptions) (result *v1alpha1.ClusterPropagationPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterpropagationpoliciesResource, clusterpropagationpoliciesKind, opts), &v1alpha1.ClusterPropagationPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterPropagationPolicyList{}
	for _, item := range obj.(*v1alpha1.ClusterPropagationPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterPropagationPolicies.
func (c *FakeClusterPropagationPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterpropagationpoliciesResource, opts))
}

// Create takes the representation of a clusterPropagationPolicy and creates it.  Returns the server's representation of the clusterPropagationPolicy, and an error, if there is any.
func (c *FakeClusterPropagationPolicies) Create(clusterPropagationPolicy *v1alpha1.ClusterPropagationPolicy) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterpropagationpoliciesResource, clusterPropagationPolicy), &v1alpha1.ClusterPropagationPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagationPolicy), err
}

// Update takes the representation of a clusterPropagationPolicy and updates it. Returns the server's representation of the clusterPropagationPolicy, and an error, if there is any.
func (c *FakeClusterPropagationPolicies) Update(clusterPropagationPolicy *v1alpha1.ClusterPropagationPolicy) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterpropagationpoliciesResource, clusterPropagationPolicy), &v1alpha1.ClusterPropagationPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagationPolicy), err
}

// Delete takes name of the clusterPropagationPolicy and deletes it. Returns an error if one occurs.
func (c *FakeClusterPropagationPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterpropagationpoliciesResource, name), &v1alpha1.ClusterPropagationPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterPropagationPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterpropagationpoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterPropagationPolicyList{})
	return err
}

// Patch applies the patch and returns the patched clusterPropagationPolicy.
func (c *FakeClusterPropagationPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterpropagationpoliciesResource, name, data, subresources...), &v1alpha1.ClusterPropagationPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterPropagationPolicy), err
}
