/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha2 "github.com/karmada-io/api/work/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceBindingsGetter has a method to return a ResourceBindingInterface.
// A group's client should implement this interface.
type ResourceBindingsGetter interface {
	ResourceBindings(namespace string) ResourceBindingInterface
}

// ResourceBindingInterface has methods to work with ResourceBinding resources.
type ResourceBindingInterface interface {
	Create(*v1alpha2.ResourceBinding) (*v1alpha2.ResourceBinding, error)
	Update(*v1alpha2.ResourceBinding) (*v1alpha2.ResourceBinding, error)
	UpdateStatus(*v1alpha2.ResourceBinding) (*v1alpha2.ResourceBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha2.ResourceBinding, error)
	List(opts v1.ListOptions) (*v1alpha2.ResourceBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ResourceBinding, err error)
	ResourceBindingExpansion
}

// resourceBindings implements ResourceBindingInterface
type resourceBindings struct {
	client rest.Interface
	ns     string
}

// newResourceBindings returns a ResourceBindings
func newResourceBindings(c *WorkV1alpha2Client, namespace string) *resourceBindings {
	return &resourceBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceBinding, and returns the corresponding resourceBinding object, and an error if there is any.
func (c *resourceBindings) Get(name string, options v1.GetOptions) (result *v1alpha2.ResourceBinding, err error) {
	result = &v1alpha2.ResourceBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceBindings that match those selectors.
func (c *resourceBindings) List(opts v1.ListOptions) (result *v1alpha2.ResourceBindingList, err error) {
	result = &v1alpha2.ResourceBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceBindings.
func (c *resourceBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resourceBinding and creates it.  Returns the server's representation of the resourceBinding, and an error, if there is any.
func (c *resourceBindings) Create(resourceBinding *v1alpha2.ResourceBinding) (result *v1alpha2.ResourceBinding, err error) {
	result = &v1alpha2.ResourceBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcebindings").
		Body(resourceBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resourceBinding and updates it. Returns the server's representation of the resourceBinding, and an error, if there is any.
func (c *resourceBindings) Update(resourceBinding *v1alpha2.ResourceBinding) (result *v1alpha2.ResourceBinding, err error) {
	result = &v1alpha2.ResourceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcebindings").
		Name(resourceBinding.Name).
		Body(resourceBinding).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *resourceBindings) UpdateStatus(resourceBinding *v1alpha2.ResourceBinding) (result *v1alpha2.ResourceBinding, err error) {
	result = &v1alpha2.ResourceBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcebindings").
		Name(resourceBinding.Name).
		SubResource("status").
		Body(resourceBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the resourceBinding and deletes it. Returns an error if one occurs.
func (c *resourceBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcebindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcebindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resourceBinding.
func (c *resourceBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.ResourceBinding, err error) {
	result = &v1alpha2.ResourceBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcebindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
