/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/karmada-io/api/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MultiClusterIngressesGetter has a method to return a MultiClusterIngressInterface.
// A group's client should implement this interface.
type MultiClusterIngressesGetter interface {
	MultiClusterIngresses(namespace string) MultiClusterIngressInterface
}

// MultiClusterIngressInterface has methods to work with MultiClusterIngress resources.
type MultiClusterIngressInterface interface {
	Create(*v1alpha1.MultiClusterIngress) (*v1alpha1.MultiClusterIngress, error)
	Update(*v1alpha1.MultiClusterIngress) (*v1alpha1.MultiClusterIngress, error)
	UpdateStatus(*v1alpha1.MultiClusterIngress) (*v1alpha1.MultiClusterIngress, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MultiClusterIngress, error)
	List(opts v1.ListOptions) (*v1alpha1.MultiClusterIngressList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MultiClusterIngress, err error)
	MultiClusterIngressExpansion
}

// multiClusterIngresses implements MultiClusterIngressInterface
type multiClusterIngresses struct {
	client rest.Interface
	ns     string
}

// newMultiClusterIngresses returns a MultiClusterIngresses
func newMultiClusterIngresses(c *NetworkingV1alpha1Client, namespace string) *multiClusterIngresses {
	return &multiClusterIngresses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the multiClusterIngress, and returns the corresponding multiClusterIngress object, and an error if there is any.
func (c *multiClusterIngresses) Get(name string, options v1.GetOptions) (result *v1alpha1.MultiClusterIngress, err error) {
	result = &v1alpha1.MultiClusterIngress{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MultiClusterIngresses that match those selectors.
func (c *multiClusterIngresses) List(opts v1.ListOptions) (result *v1alpha1.MultiClusterIngressList, err error) {
	result = &v1alpha1.MultiClusterIngressList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested multiClusterIngresses.
func (c *multiClusterIngresses) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a multiClusterIngress and creates it.  Returns the server's representation of the multiClusterIngress, and an error, if there is any.
func (c *multiClusterIngresses) Create(multiClusterIngress *v1alpha1.MultiClusterIngress) (result *v1alpha1.MultiClusterIngress, err error) {
	result = &v1alpha1.MultiClusterIngress{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		Body(multiClusterIngress).
		Do().
		Into(result)
	return
}

// Update takes the representation of a multiClusterIngress and updates it. Returns the server's representation of the multiClusterIngress, and an error, if there is any.
func (c *multiClusterIngresses) Update(multiClusterIngress *v1alpha1.MultiClusterIngress) (result *v1alpha1.MultiClusterIngress, err error) {
	result = &v1alpha1.MultiClusterIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		Name(multiClusterIngress.Name).
		Body(multiClusterIngress).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *multiClusterIngresses) UpdateStatus(multiClusterIngress *v1alpha1.MultiClusterIngress) (result *v1alpha1.MultiClusterIngress, err error) {
	result = &v1alpha1.MultiClusterIngress{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		Name(multiClusterIngress.Name).
		SubResource("status").
		Body(multiClusterIngress).
		Do().
		Into(result)
	return
}

// Delete takes name of the multiClusterIngress and deletes it. Returns an error if one occurs.
func (c *multiClusterIngresses) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *multiClusterIngresses) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("multiclusteringresses").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched multiClusterIngress.
func (c *multiClusterIngresses) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MultiClusterIngress, err error) {
	result = &v1alpha1.MultiClusterIngress{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("multiclusteringresses").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
