/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterPropagationPoliciesGetter has a method to return a ClusterPropagationPolicyInterface.
// A group's client should implement this interface.
type ClusterPropagationPoliciesGetter interface {
	ClusterPropagationPolicies() ClusterPropagationPolicyInterface
}

// ClusterPropagationPolicyInterface has methods to work with ClusterPropagationPolicy resources.
type ClusterPropagationPolicyInterface interface {
	Create(*v1alpha1.ClusterPropagationPolicy) (*v1alpha1.ClusterPropagationPolicy, error)
	Update(*v1alpha1.ClusterPropagationPolicy) (*v1alpha1.ClusterPropagationPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterPropagationPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterPropagationPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterPropagationPolicy, err error)
	ClusterPropagationPolicyExpansion
}

// clusterPropagationPolicies implements ClusterPropagationPolicyInterface
type clusterPropagationPolicies struct {
	client rest.Interface
}

// newClusterPropagationPolicies returns a ClusterPropagationPolicies
func newClusterPropagationPolicies(c *PolicyV1alpha1Client) *clusterPropagationPolicies {
	return &clusterPropagationPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterPropagationPolicy, and returns the corresponding clusterPropagationPolicy object, and an error if there is any.
func (c *clusterPropagationPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	result = &v1alpha1.ClusterPropagationPolicy{}
	err = c.client.Get().
		Resource("clusterpropagationpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterPropagationPolicies that match those selectors.
func (c *clusterPropagationPolicies) List(opts v1.ListOptions) (result *v1alpha1.ClusterPropagationPolicyList, err error) {
	result = &v1alpha1.ClusterPropagationPolicyList{}
	err = c.client.Get().
		Resource("clusterpropagationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterPropagationPolicies.
func (c *clusterPropagationPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("clusterpropagationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterPropagationPolicy and creates it.  Returns the server's representation of the clusterPropagationPolicy, and an error, if there is any.
func (c *clusterPropagationPolicies) Create(clusterPropagationPolicy *v1alpha1.ClusterPropagationPolicy) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	result = &v1alpha1.ClusterPropagationPolicy{}
	err = c.client.Post().
		Resource("clusterpropagationpolicies").
		Body(clusterPropagationPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterPropagationPolicy and updates it. Returns the server's representation of the clusterPropagationPolicy, and an error, if there is any.
func (c *clusterPropagationPolicies) Update(clusterPropagationPolicy *v1alpha1.ClusterPropagationPolicy) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	result = &v1alpha1.ClusterPropagationPolicy{}
	err = c.client.Put().
		Resource("clusterpropagationpolicies").
		Name(clusterPropagationPolicy.Name).
		Body(clusterPropagationPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterPropagationPolicy and deletes it. Returns an error if one occurs.
func (c *clusterPropagationPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterpropagationpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterPropagationPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("clusterpropagationpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterPropagationPolicy.
func (c *clusterPropagationPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterPropagationPolicy, err error) {
	result = &v1alpha1.ClusterPropagationPolicy{}
	err = c.client.Patch(pt).
		Resource("clusterpropagationpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
