/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterOverridePoliciesGetter has a method to return a ClusterOverridePolicyInterface.
// A group's client should implement this interface.
type ClusterOverridePoliciesGetter interface {
	ClusterOverridePolicies() ClusterOverridePolicyInterface
}

// ClusterOverridePolicyInterface has methods to work with ClusterOverridePolicy resources.
type ClusterOverridePolicyInterface interface {
	Create(*v1alpha1.ClusterOverridePolicy) (*v1alpha1.ClusterOverridePolicy, error)
	Update(*v1alpha1.ClusterOverridePolicy) (*v1alpha1.ClusterOverridePolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterOverridePolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterOverridePolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterOverridePolicy, err error)
	ClusterOverridePolicyExpansion
}

// clusterOverridePolicies implements ClusterOverridePolicyInterface
type clusterOverridePolicies struct {
	client rest.Interface
}

// newClusterOverridePolicies returns a ClusterOverridePolicies
func newClusterOverridePolicies(c *PolicyV1alpha1Client) *clusterOverridePolicies {
	return &clusterOverridePolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterOverridePolicy, and returns the corresponding clusterOverridePolicy object, and an error if there is any.
func (c *clusterOverridePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterOverridePolicy, err error) {
	result = &v1alpha1.ClusterOverridePolicy{}
	err = c.client.Get().
		Resource("clusteroverridepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterOverridePolicies that match those selectors.
func (c *clusterOverridePolicies) List(opts v1.ListOptions) (result *v1alpha1.ClusterOverridePolicyList, err error) {
	result = &v1alpha1.ClusterOverridePolicyList{}
	err = c.client.Get().
		Resource("clusteroverridepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterOverridePolicies.
func (c *clusterOverridePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("clusteroverridepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterOverridePolicy and creates it.  Returns the server's representation of the clusterOverridePolicy, and an error, if there is any.
func (c *clusterOverridePolicies) Create(clusterOverridePolicy *v1alpha1.ClusterOverridePolicy) (result *v1alpha1.ClusterOverridePolicy, err error) {
	result = &v1alpha1.ClusterOverridePolicy{}
	err = c.client.Post().
		Resource("clusteroverridepolicies").
		Body(clusterOverridePolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterOverridePolicy and updates it. Returns the server's representation of the clusterOverridePolicy, and an error, if there is any.
func (c *clusterOverridePolicies) Update(clusterOverridePolicy *v1alpha1.ClusterOverridePolicy) (result *v1alpha1.ClusterOverridePolicy, err error) {
	result = &v1alpha1.ClusterOverridePolicy{}
	err = c.client.Put().
		Resource("clusteroverridepolicies").
		Name(clusterOverridePolicy.Name).
		Body(clusterOverridePolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterOverridePolicy and deletes it. Returns an error if one occurs.
func (c *clusterOverridePolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusteroverridepolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterOverridePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("clusteroverridepolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterOverridePolicy.
func (c *clusterOverridePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterOverridePolicy, err error) {
	result = &v1alpha1.ClusterOverridePolicy{}
	err = c.client.Patch(pt).
		Resource("clusteroverridepolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
