/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OverridePoliciesGetter has a method to return a OverridePolicyInterface.
// A group's client should implement this interface.
type OverridePoliciesGetter interface {
	OverridePolicies(namespace string) OverridePolicyInterface
}

// OverridePolicyInterface has methods to work with OverridePolicy resources.
type OverridePolicyInterface interface {
	Create(*v1alpha1.OverridePolicy) (*v1alpha1.OverridePolicy, error)
	Update(*v1alpha1.OverridePolicy) (*v1alpha1.OverridePolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.OverridePolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.OverridePolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OverridePolicy, err error)
	OverridePolicyExpansion
}

// overridePolicies implements OverridePolicyInterface
type overridePolicies struct {
	client rest.Interface
	ns     string
}

// newOverridePolicies returns a OverridePolicies
func newOverridePolicies(c *PolicyV1alpha1Client, namespace string) *overridePolicies {
	return &overridePolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the overridePolicy, and returns the corresponding overridePolicy object, and an error if there is any.
func (c *overridePolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.OverridePolicy, err error) {
	result = &v1alpha1.OverridePolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("overridepolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OverridePolicies that match those selectors.
func (c *overridePolicies) List(opts v1.ListOptions) (result *v1alpha1.OverridePolicyList, err error) {
	result = &v1alpha1.OverridePolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("overridepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested overridePolicies.
func (c *overridePolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("overridepolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a overridePolicy and creates it.  Returns the server's representation of the overridePolicy, and an error, if there is any.
func (c *overridePolicies) Create(overridePolicy *v1alpha1.OverridePolicy) (result *v1alpha1.OverridePolicy, err error) {
	result = &v1alpha1.OverridePolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("overridepolicies").
		Body(overridePolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a overridePolicy and updates it. Returns the server's representation of the overridePolicy, and an error, if there is any.
func (c *overridePolicies) Update(overridePolicy *v1alpha1.OverridePolicy) (result *v1alpha1.OverridePolicy, err error) {
	result = &v1alpha1.OverridePolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("overridepolicies").
		Name(overridePolicy.Name).
		Body(overridePolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the overridePolicy and deletes it. Returns an error if one occurs.
func (c *overridePolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("overridepolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *overridePolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("overridepolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched overridePolicy.
func (c *overridePolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OverridePolicy, err error) {
	result = &v1alpha1.OverridePolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("overridepolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
