/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	scheme "github.com/karmada-io/api/client/clientset/versioned/scheme"
	v1alpha1 "github.com/karmada-io/api/policy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PropagationPoliciesGetter has a method to return a PropagationPolicyInterface.
// A group's client should implement this interface.
type PropagationPoliciesGetter interface {
	PropagationPolicies(namespace string) PropagationPolicyInterface
}

// PropagationPolicyInterface has methods to work with PropagationPolicy resources.
type PropagationPolicyInterface interface {
	Create(*v1alpha1.PropagationPolicy) (*v1alpha1.PropagationPolicy, error)
	Update(*v1alpha1.PropagationPolicy) (*v1alpha1.PropagationPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.PropagationPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.PropagationPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PropagationPolicy, err error)
	PropagationPolicyExpansion
}

// propagationPolicies implements PropagationPolicyInterface
type propagationPolicies struct {
	client rest.Interface
	ns     string
}

// newPropagationPolicies returns a PropagationPolicies
func newPropagationPolicies(c *PolicyV1alpha1Client, namespace string) *propagationPolicies {
	return &propagationPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the propagationPolicy, and returns the corresponding propagationPolicy object, and an error if there is any.
func (c *propagationPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.PropagationPolicy, err error) {
	result = &v1alpha1.PropagationPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagationpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PropagationPolicies that match those selectors.
func (c *propagationPolicies) List(opts v1.ListOptions) (result *v1alpha1.PropagationPolicyList, err error) {
	result = &v1alpha1.PropagationPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("propagationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested propagationPolicies.
func (c *propagationPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("propagationpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a propagationPolicy and creates it.  Returns the server's representation of the propagationPolicy, and an error, if there is any.
func (c *propagationPolicies) Create(propagationPolicy *v1alpha1.PropagationPolicy) (result *v1alpha1.PropagationPolicy, err error) {
	result = &v1alpha1.PropagationPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("propagationpolicies").
		Body(propagationPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a propagationPolicy and updates it. Returns the server's representation of the propagationPolicy, and an error, if there is any.
func (c *propagationPolicies) Update(propagationPolicy *v1alpha1.PropagationPolicy) (result *v1alpha1.PropagationPolicy, err error) {
	result = &v1alpha1.PropagationPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("propagationpolicies").
		Name(propagationPolicy.Name).
		Body(propagationPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the propagationPolicy and deletes it. Returns an error if one occurs.
func (c *propagationPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagationpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *propagationPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("propagationpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched propagationPolicy.
func (c *propagationPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.PropagationPolicy, err error) {
	result = &v1alpha1.PropagationPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("propagationpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
