// +build !ignore_autogenerated

/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	cluster "github.com/karmada-io/api/cluster"
	v1 "k8s.io/api/core/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_APIEnablement_To_cluster_APIEnablement,
		Convert_cluster_APIEnablement_To_v1alpha1_APIEnablement,
		Convert_v1alpha1_APIResource_To_cluster_APIResource,
		Convert_cluster_APIResource_To_v1alpha1_APIResource,
		Convert_v1alpha1_Cluster_To_cluster_Cluster,
		Convert_cluster_Cluster_To_v1alpha1_Cluster,
		Convert_v1alpha1_ClusterList_To_cluster_ClusterList,
		Convert_cluster_ClusterList_To_v1alpha1_ClusterList,
		Convert_v1alpha1_ClusterProxyOptions_To_cluster_ClusterProxyOptions,
		Convert_cluster_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions,
		Convert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec,
		Convert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec,
		Convert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus,
		Convert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus,
		Convert_v1alpha1_LocalSecretReference_To_cluster_LocalSecretReference,
		Convert_cluster_LocalSecretReference_To_v1alpha1_LocalSecretReference,
		Convert_v1alpha1_NodeSummary_To_cluster_NodeSummary,
		Convert_cluster_NodeSummary_To_v1alpha1_NodeSummary,
		Convert_v1alpha1_ResourceSummary_To_cluster_ResourceSummary,
		Convert_cluster_ResourceSummary_To_v1alpha1_ResourceSummary,
	)
}

func autoConvert_v1alpha1_APIEnablement_To_cluster_APIEnablement(in *APIEnablement, out *cluster.APIEnablement, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Resources = *(*[]cluster.APIResource)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha1_APIEnablement_To_cluster_APIEnablement is an autogenerated conversion function.
func Convert_v1alpha1_APIEnablement_To_cluster_APIEnablement(in *APIEnablement, out *cluster.APIEnablement, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIEnablement_To_cluster_APIEnablement(in, out, s)
}

func autoConvert_cluster_APIEnablement_To_v1alpha1_APIEnablement(in *cluster.APIEnablement, out *APIEnablement, s conversion.Scope) error {
	out.GroupVersion = in.GroupVersion
	out.Resources = *(*[]APIResource)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_cluster_APIEnablement_To_v1alpha1_APIEnablement is an autogenerated conversion function.
func Convert_cluster_APIEnablement_To_v1alpha1_APIEnablement(in *cluster.APIEnablement, out *APIEnablement, s conversion.Scope) error {
	return autoConvert_cluster_APIEnablement_To_v1alpha1_APIEnablement(in, out, s)
}

func autoConvert_v1alpha1_APIResource_To_cluster_APIResource(in *APIResource, out *cluster.APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_v1alpha1_APIResource_To_cluster_APIResource is an autogenerated conversion function.
func Convert_v1alpha1_APIResource_To_cluster_APIResource(in *APIResource, out *cluster.APIResource, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIResource_To_cluster_APIResource(in, out, s)
}

func autoConvert_cluster_APIResource_To_v1alpha1_APIResource(in *cluster.APIResource, out *APIResource, s conversion.Scope) error {
	out.Name = in.Name
	out.Kind = in.Kind
	return nil
}

// Convert_cluster_APIResource_To_v1alpha1_APIResource is an autogenerated conversion function.
func Convert_cluster_APIResource_To_v1alpha1_APIResource(in *cluster.APIResource, out *APIResource, s conversion.Scope) error {
	return autoConvert_cluster_APIResource_To_v1alpha1_APIResource(in, out, s)
}

func autoConvert_v1alpha1_Cluster_To_cluster_Cluster(in *Cluster, out *cluster.Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Cluster_To_cluster_Cluster is an autogenerated conversion function.
func Convert_v1alpha1_Cluster_To_cluster_Cluster(in *Cluster, out *cluster.Cluster, s conversion.Scope) error {
	return autoConvert_v1alpha1_Cluster_To_cluster_Cluster(in, out, s)
}

func autoConvert_cluster_Cluster_To_v1alpha1_Cluster(in *cluster.Cluster, out *Cluster, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_cluster_Cluster_To_v1alpha1_Cluster is an autogenerated conversion function.
func Convert_cluster_Cluster_To_v1alpha1_Cluster(in *cluster.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_cluster_Cluster_To_v1alpha1_Cluster(in, out, s)
}

func autoConvert_v1alpha1_ClusterList_To_cluster_ClusterList(in *ClusterList, out *cluster.ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]cluster.Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterList_To_cluster_ClusterList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterList_To_cluster_ClusterList(in *ClusterList, out *cluster.ClusterList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterList_To_cluster_ClusterList(in, out, s)
}

func autoConvert_cluster_ClusterList_To_v1alpha1_ClusterList(in *cluster.ClusterList, out *ClusterList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Cluster)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_cluster_ClusterList_To_v1alpha1_ClusterList is an autogenerated conversion function.
func Convert_cluster_ClusterList_To_v1alpha1_ClusterList(in *cluster.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_cluster_ClusterList_To_v1alpha1_ClusterList(in, out, s)
}

func autoConvert_v1alpha1_ClusterProxyOptions_To_cluster_ClusterProxyOptions(in *ClusterProxyOptions, out *cluster.ClusterProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_v1alpha1_ClusterProxyOptions_To_cluster_ClusterProxyOptions is an autogenerated conversion function.
func Convert_v1alpha1_ClusterProxyOptions_To_cluster_ClusterProxyOptions(in *ClusterProxyOptions, out *cluster.ClusterProxyOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterProxyOptions_To_cluster_ClusterProxyOptions(in, out, s)
}

func autoConvert_cluster_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in *cluster.ClusterProxyOptions, out *ClusterProxyOptions, s conversion.Scope) error {
	out.Path = in.Path
	return nil
}

// Convert_cluster_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions is an autogenerated conversion function.
func Convert_cluster_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in *cluster.ClusterProxyOptions, out *ClusterProxyOptions, s conversion.Scope) error {
	return autoConvert_cluster_ClusterProxyOptions_To_v1alpha1_ClusterProxyOptions(in, out, s)
}

func autoConvert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec(in *ClusterSpec, out *cluster.ClusterSpec, s conversion.Scope) error {
	out.SyncMode = cluster.ClusterSyncMode(in.SyncMode)
	out.APIEndpoint = in.APIEndpoint
	out.SecretRef = (*cluster.LocalSecretReference)(unsafe.Pointer(in.SecretRef))
	out.ImpersonatorSecretRef = (*cluster.LocalSecretReference)(unsafe.Pointer(in.ImpersonatorSecretRef))
	out.InsecureSkipTLSVerification = in.InsecureSkipTLSVerification
	out.ProxyURL = in.ProxyURL
	out.Provider = in.Provider
	out.Region = in.Region
	out.Zone = in.Zone
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	return nil
}

// Convert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec is an autogenerated conversion function.
func Convert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec(in *ClusterSpec, out *cluster.ClusterSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterSpec_To_cluster_ClusterSpec(in, out, s)
}

func autoConvert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec(in *cluster.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	out.SyncMode = ClusterSyncMode(in.SyncMode)
	out.APIEndpoint = in.APIEndpoint
	out.SecretRef = (*LocalSecretReference)(unsafe.Pointer(in.SecretRef))
	out.ImpersonatorSecretRef = (*LocalSecretReference)(unsafe.Pointer(in.ImpersonatorSecretRef))
	out.InsecureSkipTLSVerification = in.InsecureSkipTLSVerification
	out.ProxyURL = in.ProxyURL
	out.Provider = in.Provider
	out.Region = in.Region
	out.Zone = in.Zone
	out.Taints = *(*[]v1.Taint)(unsafe.Pointer(&in.Taints))
	return nil
}

// Convert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec is an autogenerated conversion function.
func Convert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec(in *cluster.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_cluster_ClusterSpec_To_v1alpha1_ClusterSpec(in, out, s)
}

func autoConvert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus(in *ClusterStatus, out *cluster.ClusterStatus, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.APIEnablements = *(*[]cluster.APIEnablement)(unsafe.Pointer(&in.APIEnablements))
	out.Conditions = *(*[]meta_v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.NodeSummary = (*cluster.NodeSummary)(unsafe.Pointer(in.NodeSummary))
	out.ResourceSummary = (*cluster.ResourceSummary)(unsafe.Pointer(in.ResourceSummary))
	return nil
}

// Convert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus is an autogenerated conversion function.
func Convert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus(in *ClusterStatus, out *cluster.ClusterStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterStatus_To_cluster_ClusterStatus(in, out, s)
}

func autoConvert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus(in *cluster.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	out.KubernetesVersion = in.KubernetesVersion
	out.APIEnablements = *(*[]APIEnablement)(unsafe.Pointer(&in.APIEnablements))
	out.Conditions = *(*[]meta_v1.Condition)(unsafe.Pointer(&in.Conditions))
	out.NodeSummary = (*NodeSummary)(unsafe.Pointer(in.NodeSummary))
	out.ResourceSummary = (*ResourceSummary)(unsafe.Pointer(in.ResourceSummary))
	return nil
}

// Convert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus is an autogenerated conversion function.
func Convert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus(in *cluster.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_cluster_ClusterStatus_To_v1alpha1_ClusterStatus(in, out, s)
}

func autoConvert_v1alpha1_LocalSecretReference_To_cluster_LocalSecretReference(in *LocalSecretReference, out *cluster.LocalSecretReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_LocalSecretReference_To_cluster_LocalSecretReference is an autogenerated conversion function.
func Convert_v1alpha1_LocalSecretReference_To_cluster_LocalSecretReference(in *LocalSecretReference, out *cluster.LocalSecretReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_LocalSecretReference_To_cluster_LocalSecretReference(in, out, s)
}

func autoConvert_cluster_LocalSecretReference_To_v1alpha1_LocalSecretReference(in *cluster.LocalSecretReference, out *LocalSecretReference, s conversion.Scope) error {
	out.Namespace = in.Namespace
	out.Name = in.Name
	return nil
}

// Convert_cluster_LocalSecretReference_To_v1alpha1_LocalSecretReference is an autogenerated conversion function.
func Convert_cluster_LocalSecretReference_To_v1alpha1_LocalSecretReference(in *cluster.LocalSecretReference, out *LocalSecretReference, s conversion.Scope) error {
	return autoConvert_cluster_LocalSecretReference_To_v1alpha1_LocalSecretReference(in, out, s)
}

func autoConvert_v1alpha1_NodeSummary_To_cluster_NodeSummary(in *NodeSummary, out *cluster.NodeSummary, s conversion.Scope) error {
	out.TotalNum = in.TotalNum
	out.ReadyNum = in.ReadyNum
	return nil
}

// Convert_v1alpha1_NodeSummary_To_cluster_NodeSummary is an autogenerated conversion function.
func Convert_v1alpha1_NodeSummary_To_cluster_NodeSummary(in *NodeSummary, out *cluster.NodeSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeSummary_To_cluster_NodeSummary(in, out, s)
}

func autoConvert_cluster_NodeSummary_To_v1alpha1_NodeSummary(in *cluster.NodeSummary, out *NodeSummary, s conversion.Scope) error {
	out.TotalNum = in.TotalNum
	out.ReadyNum = in.ReadyNum
	return nil
}

// Convert_cluster_NodeSummary_To_v1alpha1_NodeSummary is an autogenerated conversion function.
func Convert_cluster_NodeSummary_To_v1alpha1_NodeSummary(in *cluster.NodeSummary, out *NodeSummary, s conversion.Scope) error {
	return autoConvert_cluster_NodeSummary_To_v1alpha1_NodeSummary(in, out, s)
}

func autoConvert_v1alpha1_ResourceSummary_To_cluster_ResourceSummary(in *ResourceSummary, out *cluster.ResourceSummary, s conversion.Scope) error {
	out.Allocatable = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Allocating = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocating))
	out.Allocated = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocated))
	return nil
}

// Convert_v1alpha1_ResourceSummary_To_cluster_ResourceSummary is an autogenerated conversion function.
func Convert_v1alpha1_ResourceSummary_To_cluster_ResourceSummary(in *ResourceSummary, out *cluster.ResourceSummary, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceSummary_To_cluster_ResourceSummary(in, out, s)
}

func autoConvert_cluster_ResourceSummary_To_v1alpha1_ResourceSummary(in *cluster.ResourceSummary, out *ResourceSummary, s conversion.Scope) error {
	out.Allocatable = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocatable))
	out.Allocating = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocating))
	out.Allocated = *(*v1.ResourceList)(unsafe.Pointer(&in.Allocated))
	return nil
}

// Convert_cluster_ResourceSummary_To_v1alpha1_ResourceSummary is an autogenerated conversion function.
func Convert_cluster_ResourceSummary_To_v1alpha1_ResourceSummary(in *cluster.ResourceSummary, out *ResourceSummary, s conversion.Scope) error {
	return autoConvert_cluster_ResourceSummary_To_v1alpha1_ResourceSummary(in, out, s)
}
