/*
Copyright 2022 The Karmada Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	versioned "github.com/karmada-io/api/client/clientset/versioned"
	internalinterfaces "github.com/karmada-io/api/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/karmada-io/api/client/listers/work/v1alpha2"
	work_v1alpha2 "github.com/karmada-io/api/work/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterResourceBindingInformer provides access to a shared informer and lister for
// ClusterResourceBindings.
type ClusterResourceBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.ClusterResourceBindingLister
}

type clusterResourceBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterResourceBindingInformer constructs a new informer for ClusterResourceBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterResourceBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterResourceBindingInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterResourceBindingInformer constructs a new informer for ClusterResourceBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterResourceBindingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha2().ClusterResourceBindings().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.WorkV1alpha2().ClusterResourceBindings().Watch(options)
			},
		},
		&work_v1alpha2.ClusterResourceBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterResourceBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterResourceBindingInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterResourceBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&work_v1alpha2.ClusterResourceBinding{}, f.defaultInformer)
}

func (f *clusterResourceBindingInformer) Lister() v1alpha2.ClusterResourceBindingLister {
	return v1alpha2.NewClusterResourceBindingLister(f.Informer().GetIndexer())
}
